version: '3.9'

services:
  blog-app:
    build: .
    container_name: blog-app
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://blog-mongodb:27017/blogDB
      - PORT=5000
    depends_on:
      - blog-mongodb

  blog-mongodb:
    image: mongo:7
    container_name: blog-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
